### ISSUE TITLE
Bug report: Registration with Invalid Password Format

### ISSUE THREAD

**Issue by drozdovkostya** [ratifire/devrate-service#332]
According to the requirements, the password must contain: more than 7 characters, at least one digit, at least one letter, and no spaces. But currently, it allows entering only digits with a minimum length of 6, without any letters or special characters.

![Image](https://github.com/ratifire/devrate-service/assets/160535741/686e098f-d7d6-44c7-ab2d-ad4628e04e38)
![Image](https://github.com/ratifire/devrate-service/assets/160535741/ebc1619d-64d3-4ace-b255-a5d94e656a8a)

**Comment by DmitroLis** [comment]
In the latest version (from 10.09) the password field does not work, it is impossible to register!!

**Comment by abalmasDA** [comment]
@DmitroLis  Bug was fixed. At this moment, input password is working in the correct way

**Comment by DmitroLis** [comment]
Добре заливайте і будемо тестувати

> @DmitroLis Bug was fixed. At this moment, input password is working in the correct way

**Comment by DmitroLis** [comment]
Щось не працює із узгодженими знаками

After meeting with @kartius we agreed
Update regular expression to next one:

^(?=.[a-z])(?=.[A-Z])(?=.\d)(?=.[@$!%?&])[A-Za-z\d@$!%?&]{8,}$


https://github.com/user-attachments/assets/4216545f-d2c7-4f05-bc2c-3c59166875fa
